
name: CI -  Palindrome

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      uses: actions/setup-node@v1
      with:
          node-version: 12.x
    - run: npm install
    - run: npm install --save-dev jest
    - run: npm i @types/jest
    - run: npm test
